openapi: 3.1.0
info:
  title: Swagger Petstore
  version: 1.0.0
  description: Your project description
  license:
    name: MIT
servers:
  - url: https://leeyounghun.com
paths:
  /{slug}/:
    get:
      operationId: root_retrieve
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LyhDoc'
          description: ''
  /docs/:
    get:
      operationId: docs_list
      tags:
      - docs
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LyhDoc'
          description: ''
    post:
      operationId: docs_create
      tags:
      - docs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LyhDoc'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LyhDoc'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LyhDoc'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LyhDoc'
          description: ''
  /docs/{id}/:
    get:
      operationId: docs_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - docs
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LyhDoc'
          description: ''
    put:
      operationId: docs_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - docs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LyhDoc'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LyhDoc'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LyhDoc'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LyhDoc'
          description: ''
    patch:
      operationId: docs_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - docs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedLyhDoc'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedLyhDoc'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedLyhDoc'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LyhDoc'
          description: ''
    delete:
      operationId: docs_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - docs
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    LyhDoc:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        doc_title:
          type: string
        doc_content:
          type: string
        doc_date:
          type: string
          format: date-time
      required:
      - doc_content
      - doc_date
      - doc_title
      - id
    PatchedLyhDoc:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        doc_title:
          type: string
        doc_content:
          type: string
        doc_date:
          type: string
          format: date-time
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid